spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identify_the_news?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.dreamin.hotnews.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
server:
  port: 8080